### ISSUE TITLE
Why async feature enables Tokio dependency

### ISSUE THREAD

**Issue by Angelo13C** [dobaksz/rsntp#5]
Hi!

I want to use this crate for a project, but there's a problem: I need to use the async API to obtain the time, but I have a custom async runtime (and I don't want to depend on Tokio).

Why does the async feature automatically enable the Tokio dependency?

Thanks :)

**Comment by dobaksz** [comment]
Hi,

tokio depedency is needed for ansychronous UDP sockets, internally I'm using `tokio::net::UdpSocket`. Actually, the only function which uses it is `AsyncStpClient::synchnorize`, you can relatively easily change that function to use you own async UDP socket and then tokio dependency can be removed.

**Comment by dobaksz** [comment]
Oh, I forgot it, but there is also one more place: `ToServerAddrs` trait uses `tokio::net::ToSocketAddrs`.
